// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: proto/alkibiades.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty request messages since these endpoints require no body
type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{0}
}

type OptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OptionsRequest) Reset() {
	*x = OptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsRequest) ProtoMessage() {}

func (x *OptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsRequest.ProtoReflect.Descriptor instead.
func (*OptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{1}
}

// Response message for health check
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthy        bool            `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Time           string          `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Version        string          `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DatabaseHealth *DatabaseHealth `protobuf:"bytes,4,opt,name=database_health,json=databaseHealth,proto3" json:"database_health,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDatabaseHealth() *DatabaseHealth {
	if x != nil {
		return x.DatabaseHealth
	}
	return nil
}

// Nested message for database health details
type DatabaseHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthy       bool   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ClusterName   string `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ServerName    string `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion string `protobuf:"bytes,4,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
}

func (x *DatabaseHealth) Reset() {
	*x = DatabaseHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseHealth) ProtoMessage() {}

func (x *DatabaseHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseHealth.ProtoReflect.Descriptor instead.
func (*DatabaseHealth) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DatabaseHealth) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *DatabaseHealth) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *DatabaseHealth) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

type AggregatedOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Themes []*Theme `protobuf:"bytes,1,rep,name=themes,proto3" json:"themes,omitempty"`
}

func (x *AggregatedOptions) Reset() {
	*x = AggregatedOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregatedOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedOptions) ProtoMessage() {}

func (x *AggregatedOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedOptions.ProtoReflect.Descriptor instead.
func (*AggregatedOptions) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{4}
}

func (x *AggregatedOptions) GetThemes() []*Theme {
	if x != nil {
		return x.Themes
	}
	return nil
}

type Theme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Segments []*Segments `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *Theme) Reset() {
	*x = Theme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{5}
}

func (x *Theme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theme) GetSegments() []*Segments {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Segments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number      int32        `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Location    string       `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Coordinates *Coordinates `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *Segments) Reset() {
	*x = Segments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segments) ProtoMessage() {}

func (x *Segments) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segments.ProtoReflect.Descriptor instead.
func (*Segments) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{6}
}

func (x *Segments) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Segments) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Segments) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Segments) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{7}
}

func (x *Coordinates) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinates) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type CreationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theme   string `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Segment string `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"` // Optional
}

func (x *CreationRequest) Reset() {
	*x = CreationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationRequest) ProtoMessage() {}

func (x *CreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationRequest.ProtoReflect.Descriptor instead.
func (*CreationRequest) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{8}
}

func (x *CreationRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *CreationRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

type QuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theme       string      `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Segment     string      `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	Number      int32       `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Sentence    string      `protobuf:"bytes,4,opt,name=sentence,proto3" json:"sentence,omitempty"`       // Full Greek sentence
	Translation string      `protobuf:"bytes,5,opt,name=translation,proto3" json:"translation,omitempty"` // English translation
	ContextNote string      `protobuf:"bytes,6,opt,name=contextNote,proto3" json:"contextNote,omitempty"` // Informational text about the passage
	Intro       *Intro      `protobuf:"bytes,7,opt,name=intro,proto3" json:"intro,omitempty"`
	Quiz        []*QuizStep `protobuf:"bytes,8,rep,name=quiz,proto3" json:"quiz,omitempty"` // Quiz is polymorphic — see below
}

func (x *QuizResponse) Reset() {
	*x = QuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponse) ProtoMessage() {}

func (x *QuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponse.ProtoReflect.Descriptor instead.
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{9}
}

func (x *QuizResponse) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *QuizResponse) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *QuizResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *QuizResponse) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

func (x *QuizResponse) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *QuizResponse) GetContextNote() string {
	if x != nil {
		return x.ContextNote
	}
	return ""
}

func (x *QuizResponse) GetIntro() *Intro {
	if x != nil {
		return x.Intro
	}
	return nil
}

func (x *QuizResponse) GetQuiz() []*QuizStep {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type Intro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author     string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Work       string `protobuf:"bytes,2,opt,name=work,proto3" json:"work,omitempty"`
	Background string `protobuf:"bytes,3,opt,name=background,proto3" json:"background,omitempty"`
}

func (x *Intro) Reset() {
	*x = Intro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Intro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intro) ProtoMessage() {}

func (x *Intro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intro.ProtoReflect.Descriptor instead.
func (*Intro) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{10}
}

func (x *Intro) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Intro) GetWork() string {
	if x != nil {
		return x.Work
	}
	return ""
}

func (x *Intro) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

type QuizStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*QuizStep_Match
	//	*QuizStep_Trivia
	//	*QuizStep_Structure
	//	*QuizStep_Media
	//	*QuizStep_FinalTranslation
	Type isQuizStep_Type `protobuf_oneof:"type"`
}

func (x *QuizStep) Reset() {
	*x = QuizStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizStep) ProtoMessage() {}

func (x *QuizStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizStep.ProtoReflect.Descriptor instead.
func (*QuizStep) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{11}
}

func (m *QuizStep) GetType() isQuizStep_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *QuizStep) GetMatch() *MatchQuiz {
	if x, ok := x.GetType().(*QuizStep_Match); ok {
		return x.Match
	}
	return nil
}

func (x *QuizStep) GetTrivia() *TriviaQuiz {
	if x, ok := x.GetType().(*QuizStep_Trivia); ok {
		return x.Trivia
	}
	return nil
}

func (x *QuizStep) GetStructure() *StructureQuiz {
	if x, ok := x.GetType().(*QuizStep_Structure); ok {
		return x.Structure
	}
	return nil
}

func (x *QuizStep) GetMedia() *MediaDropQuiz {
	if x, ok := x.GetType().(*QuizStep_Media); ok {
		return x.Media
	}
	return nil
}

func (x *QuizStep) GetFinalTranslation() *TranslationStep {
	if x, ok := x.GetType().(*QuizStep_FinalTranslation); ok {
		return x.FinalTranslation
	}
	return nil
}

type isQuizStep_Type interface {
	isQuizStep_Type()
}

type QuizStep_Match struct {
	Match *MatchQuiz `protobuf:"bytes,1,opt,name=match,proto3,oneof"`
}

type QuizStep_Trivia struct {
	Trivia *TriviaQuiz `protobuf:"bytes,2,opt,name=trivia,proto3,oneof"`
}

type QuizStep_Structure struct {
	Structure *StructureQuiz `protobuf:"bytes,3,opt,name=structure,proto3,oneof"`
}

type QuizStep_Media struct {
	Media *MediaDropQuiz `protobuf:"bytes,4,opt,name=media,proto3,oneof"`
}

type QuizStep_FinalTranslation struct {
	FinalTranslation *TranslationStep `protobuf:"bytes,5,opt,name=final_translation,json=finalTranslation,proto3,oneof"`
}

func (*QuizStep_Match) isQuizStep_Type() {}

func (*QuizStep_Trivia) isQuizStep_Type() {}

func (*QuizStep_Structure) isQuizStep_Type() {}

func (*QuizStep_Media) isQuizStep_Type() {}

func (*QuizStep_FinalTranslation) isQuizStep_Type() {}

type MatchQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instruction string       `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Pairs       []*MatchPair `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *MatchQuiz) Reset() {
	*x = MatchQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQuiz) ProtoMessage() {}

func (x *MatchQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQuiz.ProtoReflect.Descriptor instead.
func (*MatchQuiz) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{12}
}

func (x *MatchQuiz) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *MatchQuiz) GetPairs() []*MatchPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type MatchPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greek  string `protobuf:"bytes,1,opt,name=greek,proto3" json:"greek,omitempty"`
	Answer string `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *MatchPair) Reset() {
	*x = MatchPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPair) ProtoMessage() {}

func (x *MatchPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPair.ProtoReflect.Descriptor instead.
func (*MatchPair) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{13}
}

func (x *MatchPair) GetGreek() string {
	if x != nil {
		return x.Greek
	}
	return ""
}

func (x *MatchPair) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type TriviaQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options  []string `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	Answer   string   `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Note     string   `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"` // optional explanation
}

func (x *TriviaQuiz) Reset() {
	*x = TriviaQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriviaQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriviaQuiz) ProtoMessage() {}

func (x *TriviaQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriviaQuiz.ProtoReflect.Descriptor instead.
func (*TriviaQuiz) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{14}
}

func (x *TriviaQuiz) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *TriviaQuiz) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TriviaQuiz) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *TriviaQuiz) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type StructureQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text     string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Question string   `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Options  []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	Answer   string   `protobuf:"bytes,5,opt,name=answer,proto3" json:"answer,omitempty"`
	Note     string   `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"` // optional
}

func (x *StructureQuiz) Reset() {
	*x = StructureQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructureQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureQuiz) ProtoMessage() {}

func (x *StructureQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureQuiz.ProtoReflect.Descriptor instead.
func (*StructureQuiz) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{15}
}

func (x *StructureQuiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StructureQuiz) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StructureQuiz) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *StructureQuiz) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *StructureQuiz) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *StructureQuiz) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type MediaDropQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instruction string        `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	MediaFiles  []*MediaEntry `protobuf:"bytes,2,rep,name=mediaFiles,proto3" json:"mediaFiles,omitempty"`
}

func (x *MediaDropQuiz) Reset() {
	*x = MediaDropQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaDropQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaDropQuiz) ProtoMessage() {}

func (x *MediaDropQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaDropQuiz.ProtoReflect.Descriptor instead.
func (*MediaDropQuiz) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{16}
}

func (x *MediaDropQuiz) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *MediaDropQuiz) GetMediaFiles() []*MediaEntry {
	if x != nil {
		return x.MediaFiles
	}
	return nil
}

type MediaEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word   string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Answer string `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"` // image filename or URL
}

func (x *MediaEntry) Reset() {
	*x = MediaEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEntry) ProtoMessage() {}

func (x *MediaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEntry.ProtoReflect.Descriptor instead.
func (*MediaEntry) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{17}
}

func (x *MediaEntry) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *MediaEntry) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type TranslationStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instruction string   `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Options     []string `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	Answer      string   `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *TranslationStep) Reset() {
	*x = TranslationStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alkibiades_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationStep) ProtoMessage() {}

func (x *TranslationStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alkibiades_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationStep.ProtoReflect.Descriptor instead.
func (*TranslationStep) Descriptor() ([]byte, []int) {
	return file_proto_alkibiades_proto_rawDescGZIP(), []int{18}
}

func (x *TranslationStep) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *TranslationStep) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TranslationStep) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_proto_alkibiades_proto protoreflect.FileDescriptor

var file_proto_alkibiades_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x22, 0x0f, 0x0a,
	0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10,
	0x0a, 0x0e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xa6, 0x01, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x0f, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f,
	0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x95, 0x01, 0x0a, 0x0e, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x47, 0x0a, 0x11, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69,
	0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x68, 0x65,
	0x6d, 0x65, 0x52, 0x06, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x05, 0x54, 0x68,
	0x65, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64,
	0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0b, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x41, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x9b, 0x02, 0x0a, 0x0c, 0x51, 0x75,
	0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68,
	0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4e, 0x6f,
	0x74, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b,
	0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x52, 0x05, 0x69,
	0x6e, 0x74, 0x72, 0x6f, 0x12, 0x31, 0x0a, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c,
	0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x53, 0x74, 0x65,
	0x70, 0x52, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x22, 0x53, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x72, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1e, 0x0a, 0x0a,
	0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xda, 0x02, 0x0a,
	0x08, 0x51, 0x75, 0x69, 0x7a, 0x53, 0x74, 0x65, 0x70, 0x12, 0x36, 0x0a, 0x05, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f,
	0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x51, 0x75, 0x69, 0x7a, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x39, 0x0a, 0x06, 0x74, 0x72, 0x69, 0x76, 0x69, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b,
	0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x72, 0x69, 0x76, 0x69, 0x61, 0x51, 0x75,
	0x69, 0x7a, 0x48, 0x00, 0x52, 0x06, 0x74, 0x72, 0x69, 0x76, 0x69, 0x61, 0x12, 0x42, 0x0a, 0x09,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62,
	0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x51,
	0x75, 0x69, 0x7a, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x3a, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62,
	0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x44, 0x72, 0x6f, 0x70, 0x51,
	0x75, 0x69, 0x7a, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x53, 0x0a, 0x11,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x48, 0x00, 0x52,
	0x10, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x63, 0x0a, 0x09, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x22, 0x39,
	0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x72, 0x65, 0x65, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x65, 0x65,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x6e, 0x0a, 0x0a, 0x54, 0x72, 0x69,
	0x76, 0x69, 0x61, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x9b, 0x01, 0x0a, 0x0d, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x72, 0x0a, 0x0d, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x44, 0x72, 0x6f, 0x70, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0a, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69,
	0x61, 0x64, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0a, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x65, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x92, 0x02, 0x0a,
	0x0a, 0x41, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x12, 0x53, 0x0a, 0x06, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61,
	0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x58, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x23, 0x2e, 0x61, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65,
	0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x26, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69,
	0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x08, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69,
	0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64,
	0x65, 0x73, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x64, 0x79, 0x73, 0x73, 0x65, 0x69, 0x61, 0x2d, 0x67, 0x72, 0x65, 0x65, 0x6b, 0x2f, 0x61,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x2f, 0x61, 0x6c, 0x6b, 0x69, 0x62, 0x69, 0x61, 0x64,
	0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_alkibiades_proto_rawDescOnce sync.Once
	file_proto_alkibiades_proto_rawDescData = file_proto_alkibiades_proto_rawDesc
)

func file_proto_alkibiades_proto_rawDescGZIP() []byte {
	file_proto_alkibiades_proto_rawDescOnce.Do(func() {
		file_proto_alkibiades_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_alkibiades_proto_rawDescData)
	})
	return file_proto_alkibiades_proto_rawDescData
}

var file_proto_alkibiades_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_alkibiades_proto_goTypes = []interface{}{
	(*HealthRequest)(nil),     // 0: apologia_alkibiades.HealthRequest
	(*OptionsRequest)(nil),    // 1: apologia_alkibiades.OptionsRequest
	(*HealthResponse)(nil),    // 2: apologia_alkibiades.HealthResponse
	(*DatabaseHealth)(nil),    // 3: apologia_alkibiades.DatabaseHealth
	(*AggregatedOptions)(nil), // 4: apologia_alkibiades.AggregatedOptions
	(*Theme)(nil),             // 5: apologia_alkibiades.Theme
	(*Segments)(nil),          // 6: apologia_alkibiades.Segments
	(*Coordinates)(nil),       // 7: apologia_alkibiades.Coordinates
	(*CreationRequest)(nil),   // 8: apologia_alkibiades.CreationRequest
	(*QuizResponse)(nil),      // 9: apologia_alkibiades.QuizResponse
	(*Intro)(nil),             // 10: apologia_alkibiades.Intro
	(*QuizStep)(nil),          // 11: apologia_alkibiades.QuizStep
	(*MatchQuiz)(nil),         // 12: apologia_alkibiades.MatchQuiz
	(*MatchPair)(nil),         // 13: apologia_alkibiades.MatchPair
	(*TriviaQuiz)(nil),        // 14: apologia_alkibiades.TriviaQuiz
	(*StructureQuiz)(nil),     // 15: apologia_alkibiades.StructureQuiz
	(*MediaDropQuiz)(nil),     // 16: apologia_alkibiades.MediaDropQuiz
	(*MediaEntry)(nil),        // 17: apologia_alkibiades.MediaEntry
	(*TranslationStep)(nil),   // 18: apologia_alkibiades.TranslationStep
}
var file_proto_alkibiades_proto_depIdxs = []int32{
	3,  // 0: apologia_alkibiades.HealthResponse.database_health:type_name -> apologia_alkibiades.DatabaseHealth
	5,  // 1: apologia_alkibiades.AggregatedOptions.themes:type_name -> apologia_alkibiades.Theme
	6,  // 2: apologia_alkibiades.Theme.segments:type_name -> apologia_alkibiades.Segments
	7,  // 3: apologia_alkibiades.Segments.coordinates:type_name -> apologia_alkibiades.Coordinates
	10, // 4: apologia_alkibiades.QuizResponse.intro:type_name -> apologia_alkibiades.Intro
	11, // 5: apologia_alkibiades.QuizResponse.quiz:type_name -> apologia_alkibiades.QuizStep
	12, // 6: apologia_alkibiades.QuizStep.match:type_name -> apologia_alkibiades.MatchQuiz
	14, // 7: apologia_alkibiades.QuizStep.trivia:type_name -> apologia_alkibiades.TriviaQuiz
	15, // 8: apologia_alkibiades.QuizStep.structure:type_name -> apologia_alkibiades.StructureQuiz
	16, // 9: apologia_alkibiades.QuizStep.media:type_name -> apologia_alkibiades.MediaDropQuiz
	18, // 10: apologia_alkibiades.QuizStep.final_translation:type_name -> apologia_alkibiades.TranslationStep
	13, // 11: apologia_alkibiades.MatchQuiz.pairs:type_name -> apologia_alkibiades.MatchPair
	17, // 12: apologia_alkibiades.MediaDropQuiz.mediaFiles:type_name -> apologia_alkibiades.MediaEntry
	0,  // 13: apologia_alkibiades.Alkibiades.Health:input_type -> apologia_alkibiades.HealthRequest
	1,  // 14: apologia_alkibiades.Alkibiades.Options:input_type -> apologia_alkibiades.OptionsRequest
	8,  // 15: apologia_alkibiades.Alkibiades.Question:input_type -> apologia_alkibiades.CreationRequest
	2,  // 16: apologia_alkibiades.Alkibiades.Health:output_type -> apologia_alkibiades.HealthResponse
	4,  // 17: apologia_alkibiades.Alkibiades.Options:output_type -> apologia_alkibiades.AggregatedOptions
	9,  // 18: apologia_alkibiades.Alkibiades.Question:output_type -> apologia_alkibiades.QuizResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_alkibiades_proto_init() }
func file_proto_alkibiades_proto_init() {
	if File_proto_alkibiades_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_alkibiades_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregatedOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Theme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Intro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriviaQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructureQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaDropQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alkibiades_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_alkibiades_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*QuizStep_Match)(nil),
		(*QuizStep_Trivia)(nil),
		(*QuizStep_Structure)(nil),
		(*QuizStep_Media)(nil),
		(*QuizStep_FinalTranslation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_alkibiades_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alkibiades_proto_goTypes,
		DependencyIndexes: file_proto_alkibiades_proto_depIdxs,
		MessageInfos:      file_proto_alkibiades_proto_msgTypes,
	}.Build()
	File_proto_alkibiades_proto = out.File
	file_proto_alkibiades_proto_rawDesc = nil
	file_proto_alkibiades_proto_goTypes = nil
	file_proto_alkibiades_proto_depIdxs = nil
}
