package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	palkibiades "github.com/odysseia-greek/apologia/alkibiades/gen/go/v1"
	pbantisthenes "github.com/odysseia-greek/apologia/antisthenes/gen/go/v1"
	pbartrippos "github.com/odysseia-greek/apologia/aristippos/gen/go/v1"
	pbkritias "github.com/odysseia-greek/apologia/kritias/gen/go/v1"
	pbkriton "github.com/odysseia-greek/apologia/kriton/gen/go/v1"
	"github.com/odysseia-greek/apologia/sokrates/graph/model"
	pbxenofon "github.com/odysseia-greek/apologia/xenofon/gen/go/v1"
)

// MediaOptions is the resolver for the mediaOptions field.
func (r *queryResolver) MediaOptions(ctx context.Context) (*model.AggregatedOptions, error) {
	return r.Handler.MediaOptions(ctx)
}

// MultipleChoiceOptions is the resolver for the multipleChoiceOptions field.
func (r *queryResolver) MultipleChoiceOptions(ctx context.Context) (*model.ThemedOptions, error) {
	return r.Handler.MultipleChoiceOptions(ctx)
}

// AuthorBasedOptions is the resolver for the authorBasedOptions field.
func (r *queryResolver) AuthorBasedOptions(ctx context.Context) (*model.AggregatedOptions, error) {
	return r.Handler.AuthorBasedOptions(ctx)
}

// DialogueOptions is the resolver for the dialogueOptions field.
func (r *queryResolver) DialogueOptions(ctx context.Context) (*model.ThemedOptions, error) {
	return r.Handler.DialogueOptions(ctx)
}

// GrammarOptions is the resolver for the grammarOptions field.
func (r *queryResolver) GrammarOptions(ctx context.Context) (*model.GrammarOptions, error) {
	return r.Handler.GrammarOptions(ctx)
}

// JourneyOptions is the resolver for the journeyOptions field.
func (r *queryResolver) JourneyOptions(ctx context.Context) (*model.JourneyOptions, error) {
	return r.Handler.JourneyOptions(ctx)
}

// MediaAnswer is the resolver for the mediaAnswer field.
func (r *queryResolver) MediaAnswer(ctx context.Context, input *model.MediaAnswerInput) (*model.ComprehensiveResponse, error) {
	pb := &pbartrippos.AnswerRequest{
		Theme:     *input.Theme,
		Set:       *input.Set,
		Segment:   *input.Segment,
		Answer:    *input.Answer,
		QuizWord:  *input.QuizWord,
		DoneAfter: *input.DoneAfter,
	}

	fromMedia, err := r.Handler.CheckMedia(ctx, pb)
	if err != nil {
		return nil, err
	}

	if *input.Comprehensive {
		fromGatherer, err := r.Handler.GatherComprehensiveResponse(ctx, *input.QuizWord)
		if err != nil {
			return nil, err
		}
		fromMedia.FoundInText = fromGatherer.FoundInText
		fromMedia.SimilarWords = fromGatherer.SimilarWords
	}

	return fromMedia, nil
}

// MediaQuiz is the resolver for the mediaQuiz field.
func (r *queryResolver) MediaQuiz(ctx context.Context, input *model.MediaQuizInput) (*model.MediaQuizResponse, error) {
	pb := &pbartrippos.CreationRequest{
		Theme:           *input.Theme,
		Set:             *input.Set,
		Segment:         *input.Segment,
		DoneAfter:       *input.DoneAfter,
		ResetProgress:   *input.ResetProgress,
		ArchiveProgress: *input.ArchiveProgress,
	}

	if input.Order != nil {
		pb.Order = *input.Order
	}

	return r.Handler.CreateMediaQuiz(ctx, pb)
}

// MultipleChoiceAnswer is the resolver for the multipleChoiceAnswer field.
func (r *queryResolver) MultipleChoiceAnswer(ctx context.Context, input *model.MultipleChoiceAnswerInput) (*model.ComprehensiveResponse, error) {
	pb := &pbkritias.AnswerRequest{
		Theme:     *input.Theme,
		Set:       *input.Set,
		Answer:    *input.Answer,
		QuizWord:  *input.QuizWord,
		DoneAfter: *input.DoneAfter,
	}

	fromMultiChoice, err := r.Handler.CheckMultipleChoice(ctx, pb)
	if err != nil {
		return nil, err
	}

	if *input.Comprehensive {
		fromGatherer, err := r.Handler.GatherComprehensiveResponse(ctx, *input.QuizWord)
		if err != nil {
			return nil, err
		}
		fromMultiChoice.FoundInText = fromGatherer.FoundInText
		fromMultiChoice.SimilarWords = fromGatherer.SimilarWords
	}

	return fromMultiChoice, nil
}

// MultipleChoiceQuiz is the resolver for the multipleChoiceQuiz field.
func (r *queryResolver) MultipleChoiceQuiz(ctx context.Context, input *model.MultipleQuizInput) (*model.MultipleChoiceResponse, error) {
	pb := &pbkritias.CreationRequest{
		Theme:           *input.Theme,
		Set:             *input.Set,
		DoneAfter:       *input.DoneAfter,
		ResetProgress:   *input.ResetProgress,
		ArchiveProgress: *input.ArchiveProgress,
	}

	if input.Order != nil {
		pb.Order = *input.Order
	}

	return r.Handler.CreateMultipleChoiceQuiz(ctx, pb)
}

// AuthorBasedAnswer is the resolver for the authorBasedAnswer field.
func (r *queryResolver) AuthorBasedAnswer(ctx context.Context, input *model.AuthorBasedAnswerInput) (*model.AuthorBasedAnswerResponse, error) {
	pb := &pbxenofon.AnswerRequest{
		Theme:     *input.Theme,
		Set:       *input.Set,
		Segment:   *input.Segment,
		Answer:    *input.Answer,
		QuizWord:  *input.QuizWord,
		DoneAfter: *input.DoneAfter,
	}

	return r.Handler.CheckAuthorBased(ctx, pb)
}

// AuthorBasedQuiz is the resolver for the authorBasedQuiz field.
func (r *queryResolver) AuthorBasedQuiz(ctx context.Context, input *model.AuthorBasedInput) (*model.AuthorBasedResponse, error) {
	pb := &pbxenofon.CreationRequest{
		Theme:           *input.Theme,
		Set:             *input.Set,
		Segment:         *input.Segment,
		DoneAfter:       *input.DoneAfter,
		ResetProgress:   *input.ResetProgress,
		ArchiveProgress: *input.ArchiveProgress,
	}

	return r.Handler.CreateAuthorBasedQuiz(ctx, pb)
}

// AuthorBasedWordForms is the resolver for the authorBasedWordForms field.
func (r *queryResolver) AuthorBasedWordForms(ctx context.Context, input *model.AuthorBasedWordFormsInput) (*model.AuthorBasedWordFormsResponse, error) {
	pb := &pbxenofon.WordFormRequest{
		Theme:   *input.Theme,
		Set:     *input.Set,
		Segment: *input.Segment,
	}

	return r.Handler.AuthorBasedWordForms(ctx, pb)
}

// DialogueAnswer is the resolver for the dialogueAnswer field.
func (r *queryResolver) DialogueAnswer(ctx context.Context, input *model.DialogueAnswerInput) (*model.DialogueAnswer, error) {
	pb := &pbkriton.AnswerRequest{
		Theme: *input.Theme,
		Set:   *input.Set,
	}

	for _, content := range input.Content {
		pb.Content = append(pb.Content, &pbkriton.DialogueContent{
			Translation: *content.Translation,
			Greek:       *content.Greek,
			Place:       *content.Place,
			Speaker:     *content.Speaker,
		})
	}

	return r.Handler.CheckDialogueQuiz(ctx, pb)
}

// DialogueQuiz is the resolver for the dialogueQuiz field.
func (r *queryResolver) DialogueQuiz(ctx context.Context, input *model.DialogueQuizInput) (*model.DialogueQuizResponse, error) {
	pb := &pbkriton.CreationRequest{
		Theme: *input.Theme,
		Set:   *input.Set,
	}

	return r.Handler.CreateDialogueQuiz(ctx, pb)
}

// GrammarQuiz is the resolver for the grammarQuiz field.
func (r *queryResolver) GrammarQuiz(ctx context.Context, input *model.GrammarQuizInput) (*model.GrammarQuizResponse, error) {
	pb := &pbantisthenes.CreationRequest{
		Theme:           *input.Theme,
		Set:             *input.Set,
		Segment:         *input.Segment,
		DoneAfter:       *input.DoneAfter,
		ResetProgress:   *input.ResetProgress,
		ArchiveProgress: *input.ArchiveProgress,
	}

	return r.Handler.CreateGrammarQuiz(ctx, pb)
}

// GrammarAnswer is the resolver for the grammarAnswer field.
func (r *queryResolver) GrammarAnswer(ctx context.Context, input *model.GrammarAnswerInput) (*model.GrammarAnswer, error) {
	pb := &pbantisthenes.AnswerRequest{
		Theme:          *input.Theme,
		Set:            *input.Set,
		Segment:        *input.Segment,
		Answer:         *input.Answer,
		QuizWord:       *input.QuizWord,
		DoneAfter:      *input.DoneAfter,
		DictionaryForm: *input.DictionaryForm,
	}

	fromGrammar, err := r.Handler.CheckGrammar(ctx, pb)
	if err != nil {
		return nil, err
	}

	if *input.Comprehensive {
		fromGatherer, err := r.Handler.GatherComprehensiveResponse(ctx, *input.QuizWord)
		if err != nil {
			return nil, err
		}
		fromGrammar.FoundInText = fromGatherer.FoundInText
		fromGrammar.SimilarWords = fromGatherer.SimilarWords
	}

	return fromGrammar, nil
}

// JourneyQuiz is the resolver for the journeyQuiz field.
func (r *queryResolver) JourneyQuiz(ctx context.Context, input *model.JourneyQuizInput) (*model.JourneySegmentQuiz, error) {
	pb := &palkibiades.CreationRequest{
		Theme:   *input.Theme,
		Segment: *input.Segment,
	}

	return r.Handler.CreateJourneySection(ctx, pb)
}
