// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: proto/kritias.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty request messages since these endpoints require no body
type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{0}
}

type OptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OptionsRequest) Reset() {
	*x = OptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsRequest) ProtoMessage() {}

func (x *OptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsRequest.ProtoReflect.Descriptor instead.
func (*OptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{1}
}

// Response message for health check
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthy        bool            `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Time           string          `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Version        string          `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DatabaseHealth *DatabaseHealth `protobuf:"bytes,4,opt,name=database_health,json=databaseHealth,proto3" json:"database_health,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDatabaseHealth() *DatabaseHealth {
	if x != nil {
		return x.DatabaseHealth
	}
	return nil
}

// Nested message for database health details
type DatabaseHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthy       bool   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ClusterName   string `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ServerName    string `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion string `protobuf:"bytes,4,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
}

func (x *DatabaseHealth) Reset() {
	*x = DatabaseHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseHealth) ProtoMessage() {}

func (x *DatabaseHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseHealth.ProtoReflect.Descriptor instead.
func (*DatabaseHealth) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DatabaseHealth) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *DatabaseHealth) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *DatabaseHealth) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

// Response message for quiz options
type AggregatedOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Themes []*Theme `protobuf:"bytes,1,rep,name=themes,proto3" json:"themes,omitempty"`
}

func (x *AggregatedOptions) Reset() {
	*x = AggregatedOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregatedOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedOptions) ProtoMessage() {}

func (x *AggregatedOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedOptions.ProtoReflect.Descriptor instead.
func (*AggregatedOptions) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{4}
}

func (x *AggregatedOptions) GetThemes() []*Theme {
	if x != nil {
		return x.Themes
	}
	return nil
}

// Structure for quiz themes
type Theme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Segments []*Segment `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *Theme) Reset() {
	*x = Theme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{5}
}

func (x *Theme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theme) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// Structure for segments within a theme
type Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxSet float32 `protobuf:"fixed32,2,opt,name=max_set,json=maxSet,proto3" json:"max_set,omitempty"`
}

func (x *Segment) Reset() {
	*x = Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{6}
}

func (x *Segment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Segment) GetMaxSet() float32 {
	if x != nil {
		return x.MaxSet
	}
	return 0
}

// Request message for creating a quiz question
type CreationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theme        string   `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Set          string   `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Segment      string   `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"` // Optional
	Order        string   `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	ExcludeWords []string `protobuf:"bytes,5,rep,name=exclude_words,json=excludeWords,proto3" json:"exclude_words,omitempty"`
}

func (x *CreationRequest) Reset() {
	*x = CreationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationRequest) ProtoMessage() {}

func (x *CreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationRequest.ProtoReflect.Descriptor instead.
func (*CreationRequest) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{7}
}

func (x *CreationRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *CreationRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *CreationRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *CreationRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *CreationRequest) GetExcludeWords() []string {
	if x != nil {
		return x.ExcludeWords
	}
	return nil
}

// Response message for quiz creation
type QuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizItem      string     `protobuf:"bytes,1,opt,name=quiz_item,json=quizItem,proto3" json:"quiz_item,omitempty"`
	NumberOfItems int32      `protobuf:"varint,2,opt,name=number_of_items,json=numberOfItems,proto3" json:"number_of_items,omitempty"`
	Options       []*Options `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *QuizResponse) Reset() {
	*x = QuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponse) ProtoMessage() {}

func (x *QuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponse.ProtoReflect.Descriptor instead.
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{8}
}

func (x *QuizResponse) GetQuizItem() string {
	if x != nil {
		return x.QuizItem
	}
	return ""
}

func (x *QuizResponse) GetNumberOfItems() int32 {
	if x != nil {
		return x.NumberOfItems
	}
	return 0
}

func (x *QuizResponse) GetOptions() []*Options {
	if x != nil {
		return x.Options
	}
	return nil
}

// Quiz options (word, audio, image)
type Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option string `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
}

func (x *Options) Reset() {
	*x = Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{9}
}

func (x *Options) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

// Request message for checking an answer
type AnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theme         string `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Set           string `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Segment       string `protobuf:"bytes,4,opt,name=segment,proto3" json:"segment,omitempty"`              // Optional
	Comprehensive bool   `protobuf:"varint,5,opt,name=comprehensive,proto3" json:"comprehensive,omitempty"` // Optional
	Answer        string `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	QuizWord      string `protobuf:"bytes,7,opt,name=quiz_word,json=quizWord,proto3" json:"quiz_word,omitempty"`
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{10}
}

func (x *AnswerRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *AnswerRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *AnswerRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *AnswerRequest) GetComprehensive() bool {
	if x != nil {
		return x.Comprehensive
	}
	return false
}

func (x *AnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AnswerRequest) GetQuizWord() string {
	if x != nil {
		return x.QuizWord
	}
	return ""
}

// Response message for answer validation
type ComprehensiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Correct      bool                 `protobuf:"varint,1,opt,name=correct,proto3" json:"correct,omitempty"`
	QuizWord     string               `protobuf:"bytes,2,opt,name=quiz_word,json=quizWord,proto3" json:"quiz_word,omitempty"`
	FoundInText  *AnalyzeTextResponse `protobuf:"bytes,3,opt,name=found_in_text,json=foundInText,proto3" json:"found_in_text,omitempty"`  // Optional
	SimilarWords []*Meros             `protobuf:"bytes,4,rep,name=similar_words,json=similarWords,proto3" json:"similar_words,omitempty"` // Optional
}

func (x *ComprehensiveResponse) Reset() {
	*x = ComprehensiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComprehensiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComprehensiveResponse) ProtoMessage() {}

func (x *ComprehensiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComprehensiveResponse.ProtoReflect.Descriptor instead.
func (*ComprehensiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{11}
}

func (x *ComprehensiveResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *ComprehensiveResponse) GetQuizWord() string {
	if x != nil {
		return x.QuizWord
	}
	return ""
}

func (x *ComprehensiveResponse) GetFoundInText() *AnalyzeTextResponse {
	if x != nil {
		return x.FoundInText
	}
	return nil
}

func (x *ComprehensiveResponse) GetSimilarWords() []*Meros {
	if x != nil {
		return x.SimilarWords
	}
	return nil
}

// Similar words structure
type Meros struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greek      string `protobuf:"bytes,1,opt,name=greek,proto3" json:"greek,omitempty"`
	English    string `protobuf:"bytes,2,opt,name=english,proto3" json:"english,omitempty"`
	Dutch      string `protobuf:"bytes,3,opt,name=dutch,proto3" json:"dutch,omitempty"`                             // Optional
	LinkedWord string `protobuf:"bytes,4,opt,name=linked_word,json=linkedWord,proto3" json:"linked_word,omitempty"` // Optional
	Original   string `protobuf:"bytes,5,opt,name=original,proto3" json:"original,omitempty"`                       // Optional
}

func (x *Meros) Reset() {
	*x = Meros{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meros) ProtoMessage() {}

func (x *Meros) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meros.ProtoReflect.Descriptor instead.
func (*Meros) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{12}
}

func (x *Meros) GetGreek() string {
	if x != nil {
		return x.Greek
	}
	return ""
}

func (x *Meros) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *Meros) GetDutch() string {
	if x != nil {
		return x.Dutch
	}
	return ""
}

func (x *Meros) GetLinkedWord() string {
	if x != nil {
		return x.LinkedWord
	}
	return ""
}

func (x *Meros) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

// Text analysis response
type AnalyzeTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rootword     string           `protobuf:"bytes,1,opt,name=rootword,proto3" json:"rootword,omitempty"`
	PartOfSpeech string           `protobuf:"bytes,2,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Conjugations []*Conjugations  `protobuf:"bytes,3,rep,name=conjugations,proto3" json:"conjugations,omitempty"`
	Texts        []*AnalyzeResult `protobuf:"bytes,4,rep,name=texts,proto3" json:"texts,omitempty"`
}

func (x *AnalyzeTextResponse) Reset() {
	*x = AnalyzeTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTextResponse) ProtoMessage() {}

func (x *AnalyzeTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTextResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzeTextResponse) GetRootword() string {
	if x != nil {
		return x.Rootword
	}
	return ""
}

func (x *AnalyzeTextResponse) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *AnalyzeTextResponse) GetConjugations() []*Conjugations {
	if x != nil {
		return x.Conjugations
	}
	return nil
}

func (x *AnalyzeTextResponse) GetTexts() []*AnalyzeResult {
	if x != nil {
		return x.Texts
	}
	return nil
}

// Conjugation details
type Conjugations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Rule string `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
}

func (x *Conjugations) Reset() {
	*x = Conjugations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conjugations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conjugations) ProtoMessage() {}

func (x *Conjugations) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conjugations.ProtoReflect.Descriptor instead.
func (*Conjugations) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{14}
}

func (x *Conjugations) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Conjugations) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

// Analysis result per text reference
type AnalyzeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReferenceLink string `protobuf:"bytes,1,opt,name=reference_link,json=referenceLink,proto3" json:"reference_link,omitempty"`
	Author        string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Book          string `protobuf:"bytes,3,opt,name=book,proto3" json:"book,omitempty"`
	Reference     string `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
	Text          *Rhema `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *AnalyzeResult) Reset() {
	*x = AnalyzeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResult) ProtoMessage() {}

func (x *AnalyzeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResult.ProtoReflect.Descriptor instead.
func (*AnalyzeResult) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{15}
}

func (x *AnalyzeResult) GetReferenceLink() string {
	if x != nil {
		return x.ReferenceLink
	}
	return ""
}

func (x *AnalyzeResult) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AnalyzeResult) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *AnalyzeResult) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *AnalyzeResult) GetText() *Rhema {
	if x != nil {
		return x.Text
	}
	return nil
}

// Text details
type Rhema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greek        string   `protobuf:"bytes,1,opt,name=greek,proto3" json:"greek,omitempty"`
	Translations []string `protobuf:"bytes,2,rep,name=translations,proto3" json:"translations,omitempty"`
	Section      string   `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
}

func (x *Rhema) Reset() {
	*x = Rhema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kritias_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rhema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rhema) ProtoMessage() {}

func (x *Rhema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kritias_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rhema.ProtoReflect.Descriptor instead.
func (*Rhema) Descriptor() ([]byte, []int) {
	return file_proto_kritias_proto_rawDescGZIP(), []int{16}
}

func (x *Rhema) GetGreek() string {
	if x != nil {
		return x.Greek
	}
	return ""
}

func (x *Rhema) GetTranslations() []string {
	if x != nil {
		return x.Translations
	}
	return nil
}

func (x *Rhema) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

var File_proto_kritias_proto protoreflect.FileDescriptor

var file_proto_kritias_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f,
	0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x0e, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61,
	0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x22, 0x95, 0x01, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x11, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2f, 0x0a,
	0x06, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73,
	0x2e, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x06, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x22, 0x52,
	0x0a, 0x05, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73,
	0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x36, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x53, 0x65, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x0c,
	0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x71, 0x75, 0x69, 0x7a, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x71, 0x75, 0x69, 0x7a, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x33, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72,
	0x69, 0x74, 0x69, 0x61, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x21, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xac, 0x01, 0x0a, 0x0d, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x76, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73,
	0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x71,
	0x75, 0x69, 0x7a, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x71, 0x75, 0x69, 0x7a, 0x57, 0x6f, 0x72, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x68, 0x65, 0x6e, 0x73, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x71, 0x75, 0x69, 0x7a, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x71, 0x75, 0x69, 0x7a, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x49, 0x0a, 0x0d, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74,
	0x69, 0x61, 0x73, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6e,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x5f,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2e, 0x4d,
	0x65, 0x72, 0x6f, 0x73, 0x52, 0x0c, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x57, 0x6f, 0x72,
	0x64, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x05, 0x4d, 0x65, 0x72, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x72, 0x65, 0x65, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x65,
	0x65, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x75, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x75, 0x74,
	0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x57,
	0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x22,
	0xd2, 0x01, 0x0a, 0x13, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x6f, 0x66, 0x5f, 0x73,
	0x70, 0x65, 0x65, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x72,
	0x74, 0x4f, 0x66, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x12, 0x42, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x6a, 0x75, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69,
	0x61, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x6a, 0x75, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x0c, 0x63, 0x6f, 0x6e, 0x6a, 0x75, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x35, 0x0a,
	0x05, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2e,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x74,
	0x65, 0x78, 0x74, 0x73, 0x22, 0x36, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x6a, 0x75, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x22, 0xad, 0x01, 0x0a,
	0x0d, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x6f,
	0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x2b, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73,
	0x2e, 0x52, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x5b, 0x0a, 0x05,
	0x52, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xd3, 0x02, 0x0a, 0x07, 0x4b, 0x72,
	0x69, 0x74, 0x69, 0x61, 0x73, 0x12, 0x4d, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12,
	0x1f, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69,
	0x61, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74,
	0x69, 0x61, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x20, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69,
	0x61, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69,
	0x74, 0x69, 0x61, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f,
	0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x69, 0x61, 0x5f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x06, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f, 0x6b,
	0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x61, 0x5f,
	0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x68, 0x65,
	0x6e, 0x73, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64,
	0x79, 0x73, 0x73, 0x65, 0x69, 0x61, 0x2d, 0x67, 0x72, 0x65, 0x65, 0x6b, 0x2f, 0x61, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x69, 0x61, 0x2f, 0x6b, 0x72, 0x69, 0x74, 0x69, 0x61, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_kritias_proto_rawDescOnce sync.Once
	file_proto_kritias_proto_rawDescData = file_proto_kritias_proto_rawDesc
)

func file_proto_kritias_proto_rawDescGZIP() []byte {
	file_proto_kritias_proto_rawDescOnce.Do(func() {
		file_proto_kritias_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kritias_proto_rawDescData)
	})
	return file_proto_kritias_proto_rawDescData
}

var file_proto_kritias_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_kritias_proto_goTypes = []interface{}{
	(*HealthRequest)(nil),         // 0: apologia_kritias.HealthRequest
	(*OptionsRequest)(nil),        // 1: apologia_kritias.OptionsRequest
	(*HealthResponse)(nil),        // 2: apologia_kritias.HealthResponse
	(*DatabaseHealth)(nil),        // 3: apologia_kritias.DatabaseHealth
	(*AggregatedOptions)(nil),     // 4: apologia_kritias.AggregatedOptions
	(*Theme)(nil),                 // 5: apologia_kritias.Theme
	(*Segment)(nil),               // 6: apologia_kritias.Segment
	(*CreationRequest)(nil),       // 7: apologia_kritias.CreationRequest
	(*QuizResponse)(nil),          // 8: apologia_kritias.QuizResponse
	(*Options)(nil),               // 9: apologia_kritias.Options
	(*AnswerRequest)(nil),         // 10: apologia_kritias.AnswerRequest
	(*ComprehensiveResponse)(nil), // 11: apologia_kritias.ComprehensiveResponse
	(*Meros)(nil),                 // 12: apologia_kritias.Meros
	(*AnalyzeTextResponse)(nil),   // 13: apologia_kritias.AnalyzeTextResponse
	(*Conjugations)(nil),          // 14: apologia_kritias.Conjugations
	(*AnalyzeResult)(nil),         // 15: apologia_kritias.AnalyzeResult
	(*Rhema)(nil),                 // 16: apologia_kritias.Rhema
}
var file_proto_kritias_proto_depIdxs = []int32{
	3,  // 0: apologia_kritias.HealthResponse.database_health:type_name -> apologia_kritias.DatabaseHealth
	5,  // 1: apologia_kritias.AggregatedOptions.themes:type_name -> apologia_kritias.Theme
	6,  // 2: apologia_kritias.Theme.segments:type_name -> apologia_kritias.Segment
	9,  // 3: apologia_kritias.QuizResponse.options:type_name -> apologia_kritias.Options
	13, // 4: apologia_kritias.ComprehensiveResponse.found_in_text:type_name -> apologia_kritias.AnalyzeTextResponse
	12, // 5: apologia_kritias.ComprehensiveResponse.similar_words:type_name -> apologia_kritias.Meros
	14, // 6: apologia_kritias.AnalyzeTextResponse.conjugations:type_name -> apologia_kritias.Conjugations
	15, // 7: apologia_kritias.AnalyzeTextResponse.texts:type_name -> apologia_kritias.AnalyzeResult
	16, // 8: apologia_kritias.AnalyzeResult.text:type_name -> apologia_kritias.Rhema
	0,  // 9: apologia_kritias.Kritias.Health:input_type -> apologia_kritias.HealthRequest
	1,  // 10: apologia_kritias.Kritias.Options:input_type -> apologia_kritias.OptionsRequest
	7,  // 11: apologia_kritias.Kritias.Question:input_type -> apologia_kritias.CreationRequest
	10, // 12: apologia_kritias.Kritias.Answer:input_type -> apologia_kritias.AnswerRequest
	2,  // 13: apologia_kritias.Kritias.Health:output_type -> apologia_kritias.HealthResponse
	4,  // 14: apologia_kritias.Kritias.Options:output_type -> apologia_kritias.AggregatedOptions
	8,  // 15: apologia_kritias.Kritias.Question:output_type -> apologia_kritias.QuizResponse
	11, // 16: apologia_kritias.Kritias.Answer:output_type -> apologia_kritias.ComprehensiveResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_kritias_proto_init() }
func file_proto_kritias_proto_init() {
	if File_proto_kritias_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kritias_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregatedOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Theme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComprehensiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meros); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzeTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conjugations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kritias_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rhema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kritias_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kritias_proto_goTypes,
		DependencyIndexes: file_proto_kritias_proto_depIdxs,
		MessageInfos:      file_proto_kritias_proto_msgTypes,
	}.Build()
	File_proto_kritias_proto = out.File
	file_proto_kritias_proto_rawDesc = nil
	file_proto_kritias_proto_goTypes = nil
	file_proto_kritias_proto_depIdxs = nil
}
