// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/aristippos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AristipposClient is the client API for Aristippos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AristipposClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error)
	Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*ComprehensiveResponse, error)
}

type aristipposClient struct {
	cc grpc.ClientConnInterface
}

func NewAristipposClient(cc grpc.ClientConnInterface) AristipposClient {
	return &aristipposClient{cc}
}

func (c *aristipposClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.Aristippos/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aristipposClient) Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error) {
	out := new(AggregatedOptions)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.Aristippos/Options", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aristipposClient) Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.Aristippos/Question", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aristipposClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*ComprehensiveResponse, error) {
	out := new(ComprehensiveResponse)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.Aristippos/Answer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AristipposServer is the server API for Aristippos service.
// All implementations must embed UnimplementedAristipposServer
// for forward compatibility
type AristipposServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Options(context.Context, *OptionsRequest) (*AggregatedOptions, error)
	Question(context.Context, *CreationRequest) (*QuizResponse, error)
	Answer(context.Context, *AnswerRequest) (*ComprehensiveResponse, error)
	mustEmbedUnimplementedAristipposServer()
}

// UnimplementedAristipposServer must be embedded to have forward compatible implementations.
type UnimplementedAristipposServer struct {
}

func (UnimplementedAristipposServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAristipposServer) Options(context.Context, *OptionsRequest) (*AggregatedOptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Options not implemented")
}
func (UnimplementedAristipposServer) Question(context.Context, *CreationRequest) (*QuizResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Question not implemented")
}
func (UnimplementedAristipposServer) Answer(context.Context, *AnswerRequest) (*ComprehensiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedAristipposServer) mustEmbedUnimplementedAristipposServer() {}

// UnsafeAristipposServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AristipposServer will
// result in compilation errors.
type UnsafeAristipposServer interface {
	mustEmbedUnimplementedAristipposServer()
}

func RegisterAristipposServer(s grpc.ServiceRegistrar, srv AristipposServer) {
	s.RegisterService(&Aristippos_ServiceDesc, srv)
}

func _Aristippos_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.Aristippos/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aristippos_Options_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServer).Options(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.Aristippos/Options",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServer).Options(ctx, req.(*OptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aristippos_Question_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServer).Question(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.Aristippos/Question",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServer).Question(ctx, req.(*CreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aristippos_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.Aristippos/Answer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aristippos_ServiceDesc is the grpc.ServiceDesc for Aristippos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aristippos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apologia_aristippos.Aristippos",
	HandlerType: (*AristipposServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Aristippos_Health_Handler,
		},
		{
			MethodName: "Options",
			Handler:    _Aristippos_Options_Handler,
		},
		{
			MethodName: "Question",
			Handler:    _Aristippos_Question_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _Aristippos_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aristippos.proto",
}
