// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/aristippos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AristipposServiceClient is the client API for AristipposService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AristipposServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error)
	Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*ComprehensiveResponse, error)
}

type aristipposServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAristipposServiceClient(cc grpc.ClientConnInterface) AristipposServiceClient {
	return &aristipposServiceClient{cc}
}

func (c *aristipposServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.AristipposService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aristipposServiceClient) Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error) {
	out := new(AggregatedOptions)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.AristipposService/Options", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aristipposServiceClient) Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.AristipposService/Question", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aristipposServiceClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*ComprehensiveResponse, error) {
	out := new(ComprehensiveResponse)
	err := c.cc.Invoke(ctx, "/apologia_aristippos.AristipposService/Answer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AristipposServiceServer is the server API for AristipposService service.
// All implementations must embed UnimplementedAristipposServiceServer
// for forward compatibility
type AristipposServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Options(context.Context, *OptionsRequest) (*AggregatedOptions, error)
	Question(context.Context, *CreationRequest) (*QuizResponse, error)
	Answer(context.Context, *AnswerRequest) (*ComprehensiveResponse, error)
	mustEmbedUnimplementedAristipposServiceServer()
}

// UnimplementedAristipposServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAristipposServiceServer struct {
}

func (UnimplementedAristipposServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAristipposServiceServer) Options(context.Context, *OptionsRequest) (*AggregatedOptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Options not implemented")
}
func (UnimplementedAristipposServiceServer) Question(context.Context, *CreationRequest) (*QuizResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Question not implemented")
}
func (UnimplementedAristipposServiceServer) Answer(context.Context, *AnswerRequest) (*ComprehensiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedAristipposServiceServer) mustEmbedUnimplementedAristipposServiceServer() {}

// UnsafeAristipposServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AristipposServiceServer will
// result in compilation errors.
type UnsafeAristipposServiceServer interface {
	mustEmbedUnimplementedAristipposServiceServer()
}

func RegisterAristipposServiceServer(s grpc.ServiceRegistrar, srv AristipposServiceServer) {
	s.RegisterService(&AristipposService_ServiceDesc, srv)
}

func _AristipposService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.AristipposService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AristipposService_Options_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServiceServer).Options(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.AristipposService/Options",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServiceServer).Options(ctx, req.(*OptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AristipposService_Question_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServiceServer).Question(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.AristipposService/Question",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServiceServer).Question(ctx, req.(*CreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AristipposService_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AristipposServiceServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_aristippos.AristipposService/Answer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AristipposServiceServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AristipposService_ServiceDesc is the grpc.ServiceDesc for AristipposService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AristipposService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apologia_aristippos.AristipposService",
	HandlerType: (*AristipposServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AristipposService_Health_Handler,
		},
		{
			MethodName: "Options",
			Handler:    _AristipposService_Options_Handler,
		},
		{
			MethodName: "Question",
			Handler:    _AristipposService_Question_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _AristipposService_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aristippos.proto",
}
