// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/xenofon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XenofonClient is the client API for Xenofon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XenofonClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error)
	Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
}

type xenofonClient struct {
	cc grpc.ClientConnInterface
}

func NewXenofonClient(cc grpc.ClientConnInterface) XenofonClient {
	return &xenofonClient{cc}
}

func (c *xenofonClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/apologia_xenofon.Xenofon/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xenofonClient) Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error) {
	out := new(AggregatedOptions)
	err := c.cc.Invoke(ctx, "/apologia_xenofon.Xenofon/Options", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xenofonClient) Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, "/apologia_xenofon.Xenofon/Question", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xenofonClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, "/apologia_xenofon.Xenofon/Answer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XenofonServer is the server API for Xenofon service.
// All implementations must embed UnimplementedXenofonServer
// for forward compatibility
type XenofonServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Options(context.Context, *OptionsRequest) (*AggregatedOptions, error)
	Question(context.Context, *CreationRequest) (*QuizResponse, error)
	Answer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	mustEmbedUnimplementedXenofonServer()
}

// UnimplementedXenofonServer must be embedded to have forward compatible implementations.
type UnimplementedXenofonServer struct {
}

func (UnimplementedXenofonServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedXenofonServer) Options(context.Context, *OptionsRequest) (*AggregatedOptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Options not implemented")
}
func (UnimplementedXenofonServer) Question(context.Context, *CreationRequest) (*QuizResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Question not implemented")
}
func (UnimplementedXenofonServer) Answer(context.Context, *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedXenofonServer) mustEmbedUnimplementedXenofonServer() {}

// UnsafeXenofonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XenofonServer will
// result in compilation errors.
type UnsafeXenofonServer interface {
	mustEmbedUnimplementedXenofonServer()
}

func RegisterXenofonServer(s grpc.ServiceRegistrar, srv XenofonServer) {
	s.RegisterService(&Xenofon_ServiceDesc, srv)
}

func _Xenofon_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XenofonServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_xenofon.Xenofon/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XenofonServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xenofon_Options_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XenofonServer).Options(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_xenofon.Xenofon/Options",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XenofonServer).Options(ctx, req.(*OptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xenofon_Question_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XenofonServer).Question(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_xenofon.Xenofon/Question",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XenofonServer).Question(ctx, req.(*CreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xenofon_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XenofonServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_xenofon.Xenofon/Answer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XenofonServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Xenofon_ServiceDesc is the grpc.ServiceDesc for Xenofon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Xenofon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apologia_xenofon.Xenofon",
	HandlerType: (*XenofonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Xenofon_Health_Handler,
		},
		{
			MethodName: "Options",
			Handler:    _Xenofon_Options_Handler,
		},
		{
			MethodName: "Question",
			Handler:    _Xenofon_Question_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _Xenofon_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/xenofon.proto",
}
