// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/anisthenes.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnisthenesClient is the client API for Anisthenes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnisthenesClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error)
	Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*ComprehensiveResponse, error)
}

type anisthenesClient struct {
	cc grpc.ClientConnInterface
}

func NewAnisthenesClient(cc grpc.ClientConnInterface) AnisthenesClient {
	return &anisthenesClient{cc}
}

func (c *anisthenesClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/apologia_anisthenes.Anisthenes/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anisthenesClient) Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*AggregatedOptions, error) {
	out := new(AggregatedOptions)
	err := c.cc.Invoke(ctx, "/apologia_anisthenes.Anisthenes/Options", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anisthenesClient) Question(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, "/apologia_anisthenes.Anisthenes/Question", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anisthenesClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*ComprehensiveResponse, error) {
	out := new(ComprehensiveResponse)
	err := c.cc.Invoke(ctx, "/apologia_anisthenes.Anisthenes/Answer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnisthenesServer is the server API for Anisthenes service.
// All implementations must embed UnimplementedAnisthenesServer
// for forward compatibility
type AnisthenesServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Options(context.Context, *OptionsRequest) (*AggregatedOptions, error)
	Question(context.Context, *CreationRequest) (*QuizResponse, error)
	Answer(context.Context, *AnswerRequest) (*ComprehensiveResponse, error)
	mustEmbedUnimplementedAnisthenesServer()
}

// UnimplementedAnisthenesServer must be embedded to have forward compatible implementations.
type UnimplementedAnisthenesServer struct {
}

func (UnimplementedAnisthenesServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAnisthenesServer) Options(context.Context, *OptionsRequest) (*AggregatedOptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Options not implemented")
}
func (UnimplementedAnisthenesServer) Question(context.Context, *CreationRequest) (*QuizResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Question not implemented")
}
func (UnimplementedAnisthenesServer) Answer(context.Context, *AnswerRequest) (*ComprehensiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedAnisthenesServer) mustEmbedUnimplementedAnisthenesServer() {}

// UnsafeAnisthenesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnisthenesServer will
// result in compilation errors.
type UnsafeAnisthenesServer interface {
	mustEmbedUnimplementedAnisthenesServer()
}

func RegisterAnisthenesServer(s grpc.ServiceRegistrar, srv AnisthenesServer) {
	s.RegisterService(&Anisthenes_ServiceDesc, srv)
}

func _Anisthenes_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnisthenesServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_anisthenes.Anisthenes/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnisthenesServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anisthenes_Options_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnisthenesServer).Options(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_anisthenes.Anisthenes/Options",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnisthenesServer).Options(ctx, req.(*OptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anisthenes_Question_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnisthenesServer).Question(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_anisthenes.Anisthenes/Question",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnisthenesServer).Question(ctx, req.(*CreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anisthenes_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnisthenesServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apologia_anisthenes.Anisthenes/Answer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnisthenesServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Anisthenes_ServiceDesc is the grpc.ServiceDesc for Anisthenes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Anisthenes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apologia_anisthenes.Anisthenes",
	HandlerType: (*AnisthenesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Anisthenes_Health_Handler,
		},
		{
			MethodName: "Options",
			Handler:    _Anisthenes_Options_Handler,
		},
		{
			MethodName: "Question",
			Handler:    _Anisthenes_Question_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _Anisthenes_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/anisthenes.proto",
}
